# Numpy, Math, and Built in Functions

- Class name
- Wayne State University
- Fall 2020

_Your Name Here_

In [47]:
# Import statements

import numpy as np
import math

In [27]:
# list of numbers

num_list = [1,2,3]
print(num_list)

[1, 2, 3]


In [32]:
# Using brackets creates lists
# Lists are good for listing things or labels, not holding data for transformation or analysis
num_list + num_list

[1, 2, 3, 1, 2, 3]

In [26]:
# array of numbers
num_array = np.array([1,2,3])
print(num_array)

[1 2 3]


In [40]:
# You can perform mathematical functions on arrays and sequences

In [34]:
num_array + num_array + num_array

array([3, 6, 9])

In [36]:
# Raise an array to the power of 2
num_array**2

array([1, 4, 9], dtype=int32)

In [39]:
# TO DO: Use the np.sqrt() function on the the array to take the square root


In [38]:
# TO DO: Use the np.log() function on the array to take the natural logarithm, assign it to a variable, and print it


In [45]:
# TO DO: Use the 'arange' function to print an array starting at 5 and ending at 10, use the link below for help
# https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html


In [53]:
# 'math' is another library of useful function
# TO DO: Use the 'exp' function from the imported math package to calculate e^1
# TO DO: Use the 'exp' function from the imported math package to calculate e^10



In [69]:
# There are some built-in functions that come with python already
num_array.sum()

6

In [73]:
print(num_array.min())

1


In [71]:
# TO DO: print the max of the array using the .max() method


In [72]:
# TO DO: Print the average of the array using the .mean() method


In [81]:
# Not that we will be using these often for this class, here is a multi dimensional array
num_mat = np.array([[1,10,100,3,5],[1,2,3,4,5]])

In [83]:
# TO DO: print the mean of the 2d array


There are plenty of useful functions in these packages, more than can be covered here.

Use the references below for more info, or simply search for what you want to do in Python.

# References

+ numpy
    + https://docs.scipy.org/doc/numpy/reference/
+ pandas
    + https://pandas.pydata.org/
+ built in functions
    + https://docs.python.org/3/library/functions.html
+ user defined functions
    + https://docs.python.org/3/tutorial/controlflow.html
+ math
    + https://docs.python.org/3/library/math.html